name: mavenbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setupjava
        uses: actions/setup-java@v6.0.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: verify
        run: mvn -B clean verify
